# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zlib-1.2.12-on-linux_64, last modified Mon Apr 18 16:55:00 2022
# ------------------------------------------------

package:
  name: zlib
  version: 1.2.12
source:
  sha256: 91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9
  url: http://zlib.net/zlib-1.2.12.tar.gz
build:
  number: '1'
  run_exports:
    - zlib >=1.2.12,<1.3.0a0
  string: h7f8727e_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - cmake-no-system 3.16.5 h295c915_1
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - make 4.2.1 h1bed415_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - ripgrep 12.1.1 0
  run:
    - libgcc-ng >=7.5.0
test:
  commands:
    - test -f ${PREFIX}/include/zlib.h
    - test -f ${PREFIX}/lib/libz.a
    - test -f ${PREFIX}/lib/libz.so
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: https://zlib.net/manual.html
  home: https://zlib.net/
  license: Zlib
  license_family: Other
  license_file: zlib.h
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - groutr
    - mingwandroid
    - msarahan
    - ocefpaf
