# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libgomp
  version: 9.3.0
source:
  path: /home/builder/ktietz/cos6/ctng-compilers-feedstock/recipe
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - __glibc
  missing_dso_whitelist:
    - '*'
  number: 17
  run_exports:
    strong:
      - _openmp_mutex >=4.5
  string: h5101ec6_17
requirements:
  host:
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - sysroot_linux-64 2.17 h57e8cba_10
  run:
    - _libgcc_mutex 0.1 main
test:
  commands:
    - test -f ${PREFIX}/lib/libgomp.so.1.0.0
    - test ! -f ${PREFIX}/lib/libgomp.so.1
  requires:
    - sysroot_linux-64
about:
  home: https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GCC OpenMP implementation.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - isuruf
